# CI WORKFLOW
# ===========
# Parallel jobs on pushes to main branches, and on all pull requests, for:
# 1. clang-format check
# 2. build, test, and analyze (clang-tidy, cppcheck, unit tests, code coverage)
# 3. typos spell check

name: CI
on:
  push:
    # List all long-running branches here that you want to run CI on:
    branches: [main, master]
  pull_request:

# Cancel redundant runs: if a new commit is pushed to a PR branch, cancel the previous runs
# for that branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # =========================
  # Job 1: clang-format check
  # =========================

  formatting:
    name: Formatting Check
    runs-on: ubuntu-latest
    permissions:
      contents: read # Recommended for checkout action
    strategy:
      matrix:
        path:
          - 'src'
          - 'include'
          - 'test'
    steps:
      - uses: actions/checkout@v6

      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.16.0
        with:
          check-path: ${{ matrix.path }}

  # ===============================
  # Job 2: build, test, and analyze
  # ===============================

  build:
    name: Build, Test, and Analyze
    runs-on: ubuntu-latest
    permissions:
      contents: read # Recommended for checkout action
      pull-requests: write # Allow commenting on PR
    steps:
      - uses: actions/checkout@v6

      # Install tools

      - name: Install CMake
        uses: lukka/get-cmake@v4.2.3

      - name: Install analysis and coverage tools
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: clang-tidy-19 cppcheck lcov python3 pipx
          version: 1.0
      - name: Install fastcov
        run: |
          pipx install fastcov

      # Install project dependencies (if any)
      - name: Install project dependencies
        run: |
          sudo apt-get install -y catch2 libspdlog-dev

      # Configure and build using CI preset from CMakePresets.json.
      # Static analysis like cppcheck and clang-tidy are run as part of the build, and the
      # findings are collected from the output.

      - name: Configure (CMake preset)
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci'

      - name: Build with static analysis (CMake preset)
        uses: lukka/run-cmake@v10
        with:
          buildPreset: 'ci'

      # Run unit tests and generate code coverage report

      - name: Run tests
        uses: lukka/run-cmake@v10
        with:
          testPreset: 'ci'

      - name: Generate code coverage report
        run: cmake --build build --target coverage

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v7.0.2
        with:
          coverage-files: build/*-fastcov.info
          minimum-coverage: 80
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: coverage-report
          update-comment: true

  # Job 3: typos spell check
  typos:
    name: Spell Check
    runs-on: ubuntu-latest
    permissions:
      contents: read # Recommended for checkout action
    steps:
      - uses: actions/checkout@v6
      - name: Check spelling
        uses: crate-ci/typos@v1.44.0
